import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, relative } from 'node:path'
import { validateLocale } from '@fluenti/core'
import { resolveLocaleCodes } from '@fluenti/core/internal'
import type { ResolvedFluentConfig } from './types'

/** Wrapper around writeFileSync with a Fluenti-specific error message. */
function writeSafe(path: string, content: string): void {
  try {
    writeFileSync(path, content, 'utf-8')
  } catch (err) {
    throw new Error(
      `[fluenti] Failed to write generated module at ${path}: ${err instanceof Error ? err.message : String(err)}`,
    )
  }
}

/**
 * Generate the server module that provides:
 * - setLocale / getI18n
 * - Trans / Plural / Select / DateTime / NumberFormat (server components)
 * - I18nProvider (async server component for layouts)
 *
 * @returns Absolute path to the generated server module.
 */
export function generateServerModule(
  projectRoot: string,
  config: ResolvedFluentConfig,
): string {
  if (config.serverModule) {
    return resolve(projectRoot, config.serverModule)
  }

  const outDir = resolve(projectRoot, config.serverModuleOutDir)
  const outPath = resolve(outDir, 'server.js')
  const dtsPath = resolve(outDir, 'server.d.ts')

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true })
  }

  const locales = resolveLocaleCodes(config.fluentiConfig.locales)
  const defaultLocale = config.fluentiConfig.defaultLocale ?? config.fluentiConfig.sourceLocale
  const compiledDir = config.fluentiConfig.compileOutDir
  const fallbackChain = config.fluentiConfig.fallbackChain
  const dateFormats = config.fluentiConfig.dateFormats
  const numberFormats = config.fluentiConfig.numberFormats
  const cookieName = escapeJsSingleQuoted(config.cookieName)
  const defaultLocaleSafe = escapeJsSingleQuoted(defaultLocale)

  for (const locale of locales) {
    validateLocale(locale, 'next-plugin')
  }

  const compiledDirAbs = resolve(projectRoot, compiledDir)
  const compiledRelative = toForwardSlash(relative(outDir, compiledDirAbs))

  const localeImports = locales
    .map((locale) => `      case '${escapeJsSingleQuoted(locale)}': return import('${compiledRelative}/${locale}')`)
    .join('\n')

  const fallbackChainStr = fallbackChain
    ? JSON.stringify(fallbackChain)
    : 'undefined'

  // Generate a 'use client' provider that imports messages statically.
  // Messages contain functions (interpolation) which can't cross the RSC boundary.
  const clientProviderPath = resolve(outDir, 'client-provider.js')

  const clientStaticImports = locales
    .map((locale) => {
      const safe = locale.replace(/[^a-zA-Z0-9]/g, '_')
      return `import ${safe} from '${compiledRelative}/${locale}'`
    })
    .join('\n')

  const clientAllMessagesEntries = locales
    .map((locale) => {
      const safe = locale.replace(/[^a-zA-Z0-9]/g, '_')
      return `'${escapeJsSingleQuoted(locale)}': ${safe}`
    })
    .join(', ')

  const dateFormatsStr = dateFormats !== undefined ? JSON.stringify(dateFormats) : 'undefined'
  const numberFormatsStr = numberFormats !== undefined ? JSON.stringify(numberFormats) : 'undefined'

  const clientProviderSource = `"use client";
// Auto-generated by @fluenti/next — do not edit
// @ts-nocheck
import { createElement } from 'react'
import { I18nProvider } from '@fluenti/react'
${clientStaticImports}

const __allMessages = { ${clientAllMessagesEntries} }
const __dateFormats = ${dateFormatsStr}
const __numberFormats = ${numberFormatsStr}

export function ClientI18nProvider({ locale, fallbackLocale, fallbackChain, children }) {
  return createElement(I18nProvider, { locale, fallbackLocale, messages: __allMessages, fallbackChain, dateFormats: __dateFormats, numberFormats: __numberFormats }, children)
}
`
  writeSafe(clientProviderPath, clientProviderSource)

  const clientProviderDtsPath = resolve(outDir, 'client-provider.d.ts')
  const clientProviderDtsSource = `// Auto-generated by @fluenti/next — do not edit
import type { ReactNode, ReactElement } from 'react'

export declare function ClientI18nProvider(props: {
  locale: string
  fallbackLocale: string
  fallbackChain?: Record<string, string[]>
  children: ReactNode
}): ReactElement
`
  writeSafe(clientProviderDtsPath, clientProviderDtsSource)

  const resolveLocaleImport = config.resolveLocale
    ? (() => {
        const absPath = resolve(projectRoot, config.resolveLocale)
        const relPath = toForwardSlash(relative(outDir, absPath))
        return `import __resolveLocale from '${relPath}'`
      })()
    : null

  const resolveLocaleFn = config.resolveLocale
    ? `resolveLocale: __resolveLocale,`
    : `resolveLocale: async () => {
    try {
      const { cookies, headers } = await import('next/headers')
      const [cookieStore, headerStore] = await Promise.all([cookies(), headers()])

      // 0. x-fluenti-locale header (set by createI18nMiddleware — most authoritative)
      const fromMiddleware = headerStore.get('x-fluenti-locale')
      if (fromMiddleware && __locales.includes(fromMiddleware)) return fromMiddleware

      // 1. Cookie (configurable name)
      const fromCookie = cookieStore.get('${cookieName}')?.value
      if (fromCookie && __locales.includes(fromCookie)) return fromCookie

      // 2. Accept-Language header
      const acceptLang = headerStore.get('accept-language')
      if (acceptLang) {
        for (const part of acceptLang.split(',')) {
          const lang = part.split(';')[0].trim()
          if (__locales.includes(lang)) return lang
          const prefix = lang.split('-')[0]
          const match = __locales.find(l => l === prefix || l.startsWith(prefix + '-'))
          if (match) return match
        }
      }

      return '${defaultLocaleSafe}'
    } catch {
      return '${defaultLocaleSafe}'
    }
  },`

  const localesArrayStr = JSON.stringify(locales)

  const moduleSource = `// Auto-generated by @fluenti/next — do not edit
// @ts-nocheck
import { createServerI18n } from '@fluenti/react/server'
import { createElement } from 'react'
${resolveLocaleImport ? `${resolveLocaleImport}\n` : ''}
const __locales = ${localesArrayStr}

const serverI18n = createServerI18n({
  loadMessages: async (locale) => {
    switch (locale) {
${localeImports}
      default: return import('${compiledRelative}/${defaultLocaleSafe}')
    }
  },
  fallbackLocale: '${defaultLocaleSafe}',
  fallbackChain: ${fallbackChainStr},
  ${resolveLocaleFn}
})

export const setLocale = serverI18n.setLocale
export const getI18n = serverI18n.getI18n
export const t = (..._args) => {
  throw new Error(
    "[fluenti] \`t\` imported from '@fluenti/next' is a compile-time API replaced at build time.\\n" +
      '  Ensure:\\n' +
      '  1. \`withFluenti()\` is configured in next.config.ts\\n' +
      '  2. The file is inside src/ (not node_modules)\\n' +
      "  3. For client components, import from '@fluenti/react'",
  )
}
export const Trans = serverI18n.Trans
export const Plural = serverI18n.Plural
export const Select = serverI18n.Select
export const DateTime = serverI18n.DateTime
export const NumberFormat = serverI18n.NumberFormat

/**
 * Async server component for root layouts.
 *
 * Sets up both server-side (React.cache) and client-side (I18nProvider) i18n.
 */
export async function I18nProvider({ locale, children }) {
  const activeLocale = (locale && locale.trim()) ? locale : '${defaultLocaleSafe}'

  // 1. Initialize server-side i18n (React.cache scoped)
  serverI18n.setLocale(activeLocale)
  await serverI18n.getI18n()

  // 2. Import the local 'use client' provider that has messages statically bundled.
  // Messages contain functions (interpolation) which can't be serialized across the RSC boundary.
  const { ClientI18nProvider } = await import('./client-provider.js')

  return createElement(ClientI18nProvider, {
    locale: activeLocale,
    fallbackLocale: '${defaultLocaleSafe}',
    fallbackChain: ${fallbackChainStr},
  }, children)
}
`

  const dtsSource = `// Auto-generated by @fluenti/next — do not edit
import type { ReactNode, ReactElement } from 'react'
import type { CompileTimeT, FluentiCoreInstanceFull } from '@fluenti/core'

export declare function setLocale(locale: string): void
export declare function getI18n(): Promise<FluentiCoreInstanceFull & { locale: string }>
export declare const t: CompileTimeT

export declare function Trans(props: {
  children: ReactNode
  id?: string
  context?: string
  comment?: string
  render?: (translation: ReactNode) => ReactNode
}): Promise<ReactElement>

export declare function Plural(props: {
  value: number
  id?: string
  context?: string
  comment?: string
  zero?: ReactNode
  one?: ReactNode
  two?: ReactNode
  few?: ReactNode
  many?: ReactNode
  other: ReactNode
  offset?: number
}): Promise<ReactElement>

export declare function Select(props: {
  value: string
  id?: string
  context?: string
  comment?: string
  other: ReactNode
  options?: Record<string, ReactNode>
  [key: string]: ReactNode | Record<string, ReactNode> | string | undefined
}): Promise<ReactElement>

export declare function DateTime(props: {
  value: Date | number
  format?: string
}): Promise<ReactElement>

export declare function NumberFormat(props: {
  value: number
  format?: string
}): Promise<ReactElement>

export declare function I18nProvider(props: {
  locale?: string
  children: ReactNode
}): Promise<ReactElement>
`

  writeSafe(outPath, moduleSource)
  writeSafe(dtsPath, dtsSource)

  // Generate Edge-safe i18n config for use in middleware
  const configModulePath = resolve(outDir, 'i18n-config.js')
  const configModuleDtsPath = resolve(outDir, 'i18n-config.d.ts')

  const configModuleSource = `// Auto-generated by @fluenti/next — do not edit
export const locales = ${localesArrayStr}
export const sourceLocale = '${defaultLocaleSafe}'
export const cookieName = '${cookieName}'
`
  writeSafe(configModulePath, configModuleSource)

  const configModuleDtsSource = `// Auto-generated by @fluenti/next — do not edit
export declare const locales: string[]
export declare const sourceLocale: string
export declare const cookieName: string
`
  writeSafe(configModuleDtsPath, configModuleDtsSource)

  return outPath
}

/** Escape a string for safe embedding inside a single-quoted JS string literal. */
function escapeJsSingleQuoted(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\0/g, '\\0')
}

function toForwardSlash(p: string): string {
  return p.split('\\').join('/')
}
