import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, relative } from 'node:path'
import { validateLocale, resolveLocaleCodes } from '@fluenti/core'
import type { ResolvedFluentConfig } from './types'

/**
 * Generate the server module that provides:
 * - setLocale / getI18n
 * - Trans / Plural / Select / DateTime / NumberFormat (server components)
 * - I18nProvider (async server component for layouts)
 *
 * @returns Absolute path to the generated server module.
 */
export function generateServerModule(
  projectRoot: string,
  config: ResolvedFluentConfig,
): string {
  if (config.serverModule) {
    return resolve(projectRoot, config.serverModule)
  }

  const outDir = resolve(projectRoot, config.serverModuleOutDir)
  const outPath = resolve(outDir, 'server.js')
  const dtsPath = resolve(outDir, 'server.d.ts')

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true })
  }

  const locales = resolveLocaleCodes(config.fluentiConfig.locales)
  const defaultLocale = config.fluentiConfig.defaultLocale ?? config.fluentiConfig.sourceLocale
  const compiledDir = config.fluentiConfig.compileOutDir
  const fallbackChain = config.fluentiConfig.fallbackChain

  for (const locale of locales) {
    validateLocale(locale, 'next-plugin')
  }

  const compiledDirAbs = resolve(projectRoot, compiledDir)
  const compiledRelative = toForwardSlash(relative(outDir, compiledDirAbs))

  const localeImports = locales
    .map((locale) => `      case '${locale}': return import('${compiledRelative}/${locale}')`)
    .join('\n')

  const fallbackChainStr = fallbackChain
    ? JSON.stringify(fallbackChain)
    : 'undefined'

  // Generate a 'use client' provider that imports messages statically.
  // Messages contain functions (interpolation) which can't cross the RSC boundary.
  const clientProviderPath = resolve(outDir, 'client-provider.js')

  const clientStaticImports = locales
    .map((locale) => {
      const safe = locale.replace(/[^a-zA-Z0-9]/g, '_')
      return `import ${safe} from '${compiledRelative}/${locale}'`
    })
    .join('\n')

  const clientAllMessagesEntries = locales
    .map((locale) => {
      const safe = locale.replace(/[^a-zA-Z0-9]/g, '_')
      return `'${locale}': ${safe}`
    })
    .join(', ')

  const clientProviderSource = `"use client";
// Auto-generated by @fluenti/next — do not edit
import { createElement } from 'react'
import { I18nProvider } from '@fluenti/react'
${clientStaticImports}

const __allMessages = { ${clientAllMessagesEntries} }

export function ClientI18nProvider({ locale, fallbackLocale, fallbackChain, children }) {
  return createElement(I18nProvider, { locale, fallbackLocale, messages: __allMessages, fallbackChain }, children)
}
`
  writeFileSync(clientProviderPath, clientProviderSource, 'utf-8')

  const resolveLocaleImport = config.resolveLocale
    ? (() => {
        const absPath = resolve(projectRoot, config.resolveLocale)
        const relPath = toForwardSlash(relative(outDir, absPath))
        return `import __resolveLocale from '${relPath}'`
      })()
    : null

  const resolveLocaleFn = config.resolveLocale
    ? `resolveLocale: __resolveLocale,`
    : `resolveLocale: async () => {
    try {
      const { cookies, headers } = await import('next/headers')
      const [cookieStore, headerStore] = await Promise.all([cookies(), headers()])

      // 1. Referer URL path segment (available in Server Action context)
      const referer = headerStore.get('referer')
      if (referer) {
        try {
          const seg = new URL(referer).pathname.split('/')[1]
          if (seg && __locales.includes(seg)) return seg
        } catch {}
      }

      // 2. Cookie (configurable name)
      const fromCookie = cookieStore.get('${config.cookieName}')?.value
      if (fromCookie && __locales.includes(fromCookie)) return fromCookie

      // 3. Accept-Language header
      const acceptLang = headerStore.get('accept-language')
      if (acceptLang) {
        for (const part of acceptLang.split(',')) {
          const lang = part.split(';')[0].trim()
          if (__locales.includes(lang)) return lang
          const prefix = lang.split('-')[0]
          const match = __locales.find(l => l === prefix || l.startsWith(prefix + '-'))
          if (match) return match
        }
      }

      return '${defaultLocale}'
    } catch {
      return '${defaultLocale}'
    }
  },`

  const localesArrayStr = JSON.stringify(locales)

  const moduleSource = `// Auto-generated by @fluenti/next — do not edit
import { createServerI18n } from '@fluenti/react/server'
import { createElement } from 'react'
${resolveLocaleImport ? `${resolveLocaleImport}\n` : ''}
const __locales = ${localesArrayStr}

const serverI18n = createServerI18n({
  loadMessages: async (locale) => {
    switch (locale) {
${localeImports}
      default: return import('${compiledRelative}/${defaultLocale}')
    }
  },
  fallbackLocale: '${defaultLocale}',
  fallbackChain: ${fallbackChainStr},
  ${resolveLocaleFn}
})

export const setLocale = serverI18n.setLocale
export const getI18n = serverI18n.getI18n
export const t = (..._args) => {
  throw new Error(
    "[fluenti] \`t\` imported from '@fluenti/next' is a compile-time API replaced at build time.\\n" +
      '  Ensure:\\n' +
      '  1. \`withFluenti()\` is configured in next.config.ts\\n' +
      '  2. The file is inside src/ (not node_modules)\\n' +
      "  3. For client components, import from '@fluenti/react'",
  )
}
export const Trans = serverI18n.Trans
export const Plural = serverI18n.Plural
export const Select = serverI18n.Select
export const DateTime = serverI18n.DateTime
export const NumberFormat = serverI18n.NumberFormat

/**
 * Async server component for root layouts.
 *
 * Sets up both server-side (React.cache) and client-side (I18nProvider) i18n.
 */
export async function I18nProvider({ locale, children }) {
  const activeLocale = (locale && locale.trim()) ? locale : '${defaultLocale}'

  // 1. Initialize server-side i18n (React.cache scoped)
  serverI18n.setLocale(activeLocale)
  await serverI18n.getI18n()

  // 2. Import the local 'use client' provider that has messages statically bundled.
  // Messages contain functions (interpolation) which can't be serialized across the RSC boundary.
  const { ClientI18nProvider } = await import('./client-provider.js')

  return createElement(ClientI18nProvider, {
    locale: activeLocale,
    fallbackLocale: '${defaultLocale}',
    fallbackChain: ${fallbackChainStr},
  }, children)
}
`

  const dtsSource = `// Auto-generated by @fluenti/next — do not edit
import type { ReactNode, ReactElement } from 'react'
import type { CompileTimeT, FluentInstanceExtended } from '@fluenti/core'

export declare function setLocale(locale: string): void
export declare function getI18n(): Promise<FluentInstanceExtended & { locale: string }>
export declare const t: CompileTimeT

export declare function Trans(props: {
  children: ReactNode
  id?: string
  context?: string
  comment?: string
  render?: (translation: ReactNode) => ReactNode
}): Promise<ReactElement>

export declare function Plural(props: {
  value: number
  id?: string
  context?: string
  comment?: string
  zero?: ReactNode
  one?: ReactNode
  two?: ReactNode
  few?: ReactNode
  many?: ReactNode
  other: ReactNode
  offset?: number
}): Promise<ReactElement>

export declare function Select(props: {
  value: string
  id?: string
  context?: string
  comment?: string
  other: ReactNode
  options?: Record<string, ReactNode>
  [key: string]: ReactNode | Record<string, ReactNode> | string | undefined
}): Promise<ReactElement>

export declare function DateTime(props: {
  value: Date | number
  style?: string
}): Promise<ReactElement>

export declare function NumberFormat(props: {
  value: number
  style?: string
}): Promise<ReactElement>

export declare function I18nProvider(props: {
  locale?: string
  children: ReactNode
}): Promise<ReactElement>
`

  writeFileSync(outPath, moduleSource, 'utf-8')
  writeFileSync(dtsPath, dtsSource, 'utf-8')

  return outPath
}

function toForwardSlash(p: string): string {
  return p.split('\\').join('/')
}
