// Auto-generated by @fluenti/next — do not edit
import type { ReactNode, ReactElement } from 'react'
import type { AllMessages, Messages } from '@fluenti/core'

export declare function ClientI18nProvider(props: {
  locale: string
  fallbackLocale: string
  messages: AllMessages
  loadMessages: (locale: string) => Promise<Messages | { default: Messages }>
  fallbackChain?: Record<string, string[]>
  children: ReactNode
}): ReactElement
