/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RichtextRouteImport } from './routes/richtext'
import { Route as PluralsRouteImport } from './routes/plurals'
import { Route as IndexRouteImport } from './routes/index'

const RichtextRoute = RichtextRouteImport.update({
  id: '/richtext',
  path: '/richtext',
  getParentRoute: () => rootRouteImport,
} as any)
const PluralsRoute = PluralsRouteImport.update({
  id: '/plurals',
  path: '/plurals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plurals': typeof PluralsRoute
  '/richtext': typeof RichtextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plurals': typeof PluralsRoute
  '/richtext': typeof RichtextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plurals': typeof PluralsRoute
  '/richtext': typeof RichtextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plurals' | '/richtext'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plurals' | '/richtext'
  id: '__root__' | '/' | '/plurals' | '/richtext'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PluralsRoute: typeof PluralsRoute
  RichtextRoute: typeof RichtextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/richtext': {
      id: '/richtext'
      path: '/richtext'
      fullPath: '/richtext'
      preLoaderRoute: typeof RichtextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plurals': {
      id: '/plurals'
      path: '/plurals'
      fullPath: '/plurals'
      preLoaderRoute: typeof PluralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PluralsRoute: PluralsRoute,
  RichtextRoute: RichtextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
