/**
 * SSR utilities and locale parsing edge cases — E2E tests
 *
 * Exercises getSSRLocaleScript, getHydratedLocale, detectLocale,
 * parseLocale, negotiateLocale, validateLocale directly, plus
 * corrupted catalog handling via the CLI.
 */
import { describe, it, expect, afterEach, beforeEach } from 'vitest'
import { execSync } from 'node:child_process'
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { tmpdir } from 'node:os'

import { detectLocale, getSSRLocaleScript, getHydratedLocale } from '../packages/core/src/ssr'
import { parseLocale, negotiateLocale, validateLocale } from '../packages/core/src/locale'

const CLI = join(import.meta.dirname, '../packages/cli/dist/cli.js')

// ── helpers for CLI tests ──────────────────────────────────────────────────

function createProject(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), 'fluenti-ssr-edge-'))
  for (const [relPath, content] of Object.entries(files)) {
    const abs = join(dir, relPath)
    mkdirSync(dirname(abs), { recursive: true })
    writeFileSync(abs, content, 'utf-8')
  }
  return dir
}

function cliEnv(): Record<string, string> {
  const env: Record<string, string> = {}
  for (const [key, value] of Object.entries(process.env)) {
    if (value === undefined) continue
    if (key.startsWith('VITEST')) continue
    if (key === 'TEST') continue
    env[key] = value
  }
  env.FORCE_COLOR = '0'
  env.NODE_ENV = 'production'
  return env
}

function makeConfig(
  locales = ['en', 'ja'],
  format: 'json' | 'po' = 'json',
): string {
  return `export default {
  sourceLocale: 'en',
  locales: ${JSON.stringify(locales)},
  catalogDir: './locales',
  format: '${format}',
  include: ['./src/**/*.{ts,tsx}'],
  compileOutDir: './src/locales/compiled',
}\n`
}

// ── 1. getSSRLocaleScript() direct output verification ─────────────────────

describe('getSSRLocaleScript() direct output', () => {
  it('returns a <script> tag with the locale value', () => {
    const result = getSSRLocaleScript('en')
    expect(result).toBe('<script>window.__FLUENTI_LOCALE__="en"</script>')
  })

  it('returns a <script> tag for a complex locale', () => {
    const result = getSSRLocaleScript('zh-CN')
    expect(result).toContain('zh-CN')
    expect(result).toMatch(/^<script>window\.__FLUENTI_LOCALE__="zh-CN"<\/script>$/)
  })

  it('escapes locale values to prevent XSS via locale name', () => {
    // Angle brackets, ampersands, quotes, and backslashes should all be escaped
    // validateLocale will reject truly malicious strings, but we test the
    // escaping layer independently by checking known-safe locales that
    // contain characters that would be dangerous unescaped in HTML.
    const result = getSSRLocaleScript('ja')
    // The output must not contain unescaped angle brackets outside the tag itself
    const innerContent = result.replace(/^<script>/, '').replace(/<\/script>$/, '')
    expect(innerContent).not.toMatch(/<(?!\\u003c)/)
  })

  it('custom key option changes the window variable name', () => {
    const result = getSSRLocaleScript('ja', { key: '__MY_APP_LOCALE__' })
    expect(result).toBe('<script>window.__MY_APP_LOCALE__="ja"</script>')
  })

  it('throws for empty locale string', () => {
    expect(() => getSSRLocaleScript('')).toThrow()
  })

  it('throws for invalid locale string (XSS attempt)', () => {
    expect(() => getSSRLocaleScript('<script>alert(1)</script>')).toThrow()
  })

  it('throws for locale exceeding max length', () => {
    const longLocale = 'a'.repeat(256)
    expect(() => getSSRLocaleScript(longLocale)).toThrow(/exceeds maximum length/)
  })

  it('throws for invalid custom key (not a JS identifier)', () => {
    expect(() => getSSRLocaleScript('en', { key: 'not valid!' })).toThrow(/Invalid SSR key/)
  })
})

// ── 2. getHydratedLocale() round-trip ──────────────────────────────────────

describe('getHydratedLocale() round-trip', () => {
  const DEFAULT_KEY = '__FLUENTI_LOCALE__'
  const CUSTOM_KEY = '__MY_APP_LOCALE__'

  beforeEach(() => {
    // Ensure we have a window-like global
    if (typeof globalThis.window === 'undefined') {
      ;(globalThis as any).window = globalThis
    }
  })

  afterEach(() => {
    // Clean up any injected keys
    delete (globalThis as any)[DEFAULT_KEY]
    delete (globalThis as any)[CUSTOM_KEY]
  })

  it('script generated by getSSRLocaleScript("ja") round-trips through getHydratedLocale()', () => {
    // Simulate what the SSR script does: set window.__FLUENTI_LOCALE__ = "ja"
    const script = getSSRLocaleScript('ja')
    expect(script).toContain('"ja"')

    // Simulate the script execution
    ;(globalThis as any)[DEFAULT_KEY] = 'ja'
    const result = getHydratedLocale()
    expect(result).toBe('ja')
  })

  it('returns fallback ("en" by default) when no script was injected', () => {
    // Ensure the key does not exist
    delete (globalThis as any)[DEFAULT_KEY]
    const result = getHydratedLocale()
    expect(result).toBe('en')
  })

  it('returns custom fallback when no script was injected', () => {
    delete (globalThis as any)[DEFAULT_KEY]
    const result = getHydratedLocale('fr')
    expect(result).toBe('fr')
  })

  it('custom key round-trip works', () => {
    ;(globalThis as any)[CUSTOM_KEY] = 'zh-CN'
    const result = getHydratedLocale('en', { key: CUSTOM_KEY })
    expect(result).toBe('zh-CN')
  })

  it('custom key returns fallback when key not set', () => {
    const result = getHydratedLocale('de', { key: CUSTOM_KEY })
    expect(result).toBe('de')
  })
})

// ── 3. detectLocale() edge cases ───────────────────────────────────────────

describe('detectLocale() edge cases', () => {
  const available = ['en', 'ja', 'zh-CN', 'fr', 'de'] as const
  const fallback = 'en'

  it('Accept-Language header > 1024 characters is truncated but still parsed', () => {
    // Build a very long header: many locales repeated
    const segments: string[] = []
    for (let i = 0; i < 200; i++) {
      segments.push(`ja;q=0.${String(900 - i).padStart(3, '0')}`)
    }
    const longHeader = segments.join(',')
    expect(longHeader.length).toBeGreaterThan(1024)

    const result = detectLocale({
      headers: { 'Accept-Language': longHeader },
      available: [...available],
      fallback,
    })
    // Should still resolve to 'ja' since all entries are 'ja'
    expect(result).toBe('ja')
  })

  it('malformed Accept-Language: "en;q=abc" skips invalid entry', () => {
    const result = detectLocale({
      headers: { 'Accept-Language': 'en;q=abc,ja;q=0.9' },
      available: [...available],
      fallback,
    })
    // q=abc parses as NaN, which becomes q=0 -> filtered out. 'ja' remains.
    expect(result).toBe('ja')
  })

  it('malformed Accept-Language: empty string returns fallback', () => {
    const result = detectLocale({
      headers: { 'Accept-Language': '' },
      available: [...available],
      fallback,
    })
    expect(result).toBe('en')
  })

  it('malformed Accept-Language: ";;;" returns fallback', () => {
    const result = detectLocale({
      headers: { 'Accept-Language': ';;;' },
      available: [...available],
      fallback,
    })
    expect(result).toBe('en')
  })

  it('multiple q=1.0 locales: first listed wins', () => {
    const result = detectLocale({
      headers: { 'Accept-Language': 'ja,zh-CN,en' },
      available: [...available],
      fallback,
    })
    // All have implicit q=1.0 — sorted stably, first one wins
    expect(result).toBe('ja')
  })

  it('mixed case header name in record object works (case-insensitive)', () => {
    const result = detectLocale({
      headers: { 'ACCEPT-LANGUAGE': 'ja;q=0.9' },
      available: [...available],
      fallback,
    })
    expect(result).toBe('ja')
  })

  it('Headers object (Web API) works', () => {
    const headers = new Headers({ 'Accept-Language': 'de;q=0.8,fr;q=0.9' })
    const result = detectLocale({
      headers,
      available: [...available],
      fallback,
    })
    expect(result).toBe('fr')
  })

  it('cookie with locale value works', () => {
    const result = detectLocale({
      cookie: 'ja',
      available: [...available],
      fallback,
    })
    expect(result).toBe('ja')
  })

  it('cookie with unknown locale falls through to next source', () => {
    const result = detectLocale({
      cookie: 'xx-unknown',
      query: 'fr',
      available: [...available],
      fallback,
    })
    expect(result).toBe('fr')
  })

  it('path detection: "/zh-CN/about" returns "zh-CN"', () => {
    const result = detectLocale({
      path: 'zh-CN',
      available: [...available],
      fallback,
    })
    expect(result).toBe('zh-CN')
  })

  it('path detection: undefined path falls through to fallback', () => {
    const result = detectLocale({
      available: [...available],
      fallback,
    })
    expect(result).toBe('en')
  })

  it('query detection: locale=ja returns "ja"', () => {
    const result = detectLocale({
      query: 'ja',
      available: [...available],
      fallback,
    })
    expect(result).toBe('ja')
  })

  it('priority: cookie > query > path > Accept-Language > fallback', () => {
    // All sources provided; cookie should win
    const result = detectLocale({
      cookie: 'de',
      query: 'fr',
      path: 'ja',
      headers: { 'Accept-Language': 'zh-CN' },
      available: [...available],
      fallback,
    })
    expect(result).toBe('de')
  })

  it('priority: query wins when no cookie', () => {
    const result = detectLocale({
      query: 'fr',
      path: 'ja',
      headers: { 'Accept-Language': 'zh-CN' },
      available: [...available],
      fallback,
    })
    expect(result).toBe('fr')
  })

  it('priority: path wins when no cookie or query', () => {
    const result = detectLocale({
      path: 'ja',
      headers: { 'Accept-Language': 'zh-CN' },
      available: [...available],
      fallback,
    })
    expect(result).toBe('ja')
  })

  it('priority: Accept-Language wins when no cookie, query, or path', () => {
    const result = detectLocale({
      headers: { 'Accept-Language': 'zh-CN' },
      available: [...available],
      fallback,
    })
    expect(result).toBe('zh-CN')
  })

  it('wildcard (*) in Accept-Language is ignored', () => {
    const result = detectLocale({
      headers: { 'Accept-Language': '*;q=0.5' },
      available: [...available],
      fallback,
    })
    // * is filtered out, fallback returned
    expect(result).toBe('en')
  })

  it('q=0 locale is excluded (not acceptable per RFC 7231)', () => {
    const result = detectLocale({
      headers: { 'Accept-Language': 'ja;q=0,fr;q=0.5' },
      available: [...available],
      fallback,
    })
    // ja has q=0 (excluded), fr wins
    expect(result).toBe('fr')
  })
})

// ── 4. BCP 47 parsing edge cases ──────────────────────────────────────────

describe('parseLocale() BCP 47 edge cases', () => {
  it('zh-Hans-CN (language + script + region) parsed correctly', () => {
    const parsed = parseLocale('zh-Hans-CN')
    expect(parsed.language).toBe('zh')
    expect(parsed.script).toBe('Hans')
    expect(parsed.region).toBe('CN')
  })

  it('zh-Hant-TW parsed correctly', () => {
    const parsed = parseLocale('zh-Hant-TW')
    expect(parsed.language).toBe('zh')
    expect(parsed.script).toBe('Hant')
    expect(parsed.region).toBe('TW')
  })

  it('sr-Latn-RS (Serbian Latin) parsed correctly', () => {
    const parsed = parseLocale('sr-Latn-RS')
    expect(parsed.language).toBe('sr')
    expect(parsed.script).toBe('Latn')
    expect(parsed.region).toBe('RS')
  })

  it('en-Latn-US: script=Latn, region=US', () => {
    const parsed = parseLocale('en-Latn-US')
    expect(parsed.language).toBe('en')
    expect(parsed.script).toBe('Latn')
    expect(parsed.region).toBe('US')
  })

  it('simple language code: "en"', () => {
    const parsed = parseLocale('en')
    expect(parsed.language).toBe('en')
    expect(parsed.script).toBeUndefined()
    expect(parsed.region).toBeUndefined()
  })

  it('language + region: "en-US"', () => {
    const parsed = parseLocale('en-US')
    expect(parsed.language).toBe('en')
    expect(parsed.script).toBeUndefined()
    expect(parsed.region).toBe('US')
  })

  it('language + script only: "zh-Hans"', () => {
    const parsed = parseLocale('zh-Hans')
    expect(parsed.language).toBe('zh')
    expect(parsed.script).toBe('Hans')
    expect(parsed.region).toBeUndefined()
  })

  it('normalizes language to lowercase', () => {
    const parsed = parseLocale('EN-US')
    expect(parsed.language).toBe('en')
    expect(parsed.region).toBe('US')
  })

  it('normalizes script to title case', () => {
    const parsed = parseLocale('zh-hans-CN')
    expect(parsed.language).toBe('zh')
    expect(parsed.script).toBe('Hans')
    expect(parsed.region).toBe('CN')
  })
})

describe('negotiateLocale() edge cases', () => {
  it('zh-Hans-CN matches zh-CN (language + region, ignoring script)', () => {
    const result = negotiateLocale('zh-Hans-CN', ['zh-CN', 'zh-TW', 'en'])
    expect(result).toBe('zh-CN')
  })

  it('zh-Hans matches zh-CN (language prefix match)', () => {
    const result = negotiateLocale('zh-Hans', ['zh-CN', 'en'])
    expect(result).toBe('zh-CN')
  })

  it('en-GB falls back to en-US or en (region fallback)', () => {
    const result = negotiateLocale('en-GB', ['en-US', 'en', 'fr'])
    // en-GB has no exact match; language-only match finds first 'en-*' entry
    expect(['en-US', 'en']).toContain(result)
  })

  it('returns fallback when no match found', () => {
    const result = negotiateLocale('ko', ['en', 'fr', 'de'], 'en')
    expect(result).toBe('en')
  })

  it('returns first available when no match and no fallback', () => {
    const result = negotiateLocale('ko', ['en', 'fr', 'de'])
    expect(result).toBe('en')
  })

  it('handles array of requested locales', () => {
    const result = negotiateLocale(['ko', 'ja', 'en'], ['en', 'ja', 'fr'])
    // 'ko' no match, 'ja' matches
    expect(result).toBe('ja')
  })

  it('exact match is preferred over prefix match', () => {
    const result = negotiateLocale('en', ['en-US', 'en', 'en-GB'])
    expect(result).toBe('en')
  })

  it('case-insensitive matching works', () => {
    const result = negotiateLocale('EN-US', ['en-us', 'fr'])
    expect(result).toBe('en-us')
  })

  it('throws when no available locales and no requested locales', () => {
    expect(() => negotiateLocale([], [])).toThrow(/cannot negotiate locale/)
  })
})

describe('validateLocale() edge cases', () => {
  it('throws for empty string', () => {
    expect(() => validateLocale('', 'test')).toThrow(/non-empty string/)
  })

  it('throws for whitespace-only string', () => {
    expect(() => validateLocale('   ', 'test')).toThrow(/non-empty string/)
  })

  it('throws for "not a locale!!!"', () => {
    expect(() => validateLocale('not a locale!!!', 'test')).toThrow(/valid BCP 47/)
  })

  it('throws for string with spaces', () => {
    expect(() => validateLocale('en US', 'test')).toThrow(/valid BCP 47/)
  })

  it('throws for numeric-only string', () => {
    expect(() => validateLocale('123', 'test')).toThrow(/valid BCP 47/)
  })

  it('does not throw for "en"', () => {
    expect(() => validateLocale('en', 'test')).not.toThrow()
  })

  it('does not throw for "en-US"', () => {
    expect(() => validateLocale('en-US', 'test')).not.toThrow()
  })

  it('does not throw for "zh-Hans-CN"', () => {
    expect(() => validateLocale('zh-Hans-CN', 'test')).not.toThrow()
  })

  it('does not throw for three-letter language code "jpn"', () => {
    expect(() => validateLocale('jpn', 'test')).not.toThrow()
  })

  it('includes context in error message', () => {
    expect(() => validateLocale('!!!', 'myFunction')).toThrow(/myFunction/)
  })
})

// ── 5. Corrupted catalog handling (via CLI compile) ────────────────────────

describe('Corrupted catalog handling', () => {
  let tmpDir: string

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true })
  })

  it('JSON catalog with invalid JSON syntax: compile reports error, does not crash', () => {
    tmpDir = createProject({
      'fluenti.config.ts': makeConfig(['en', 'ja']),
      'locales/en.json': '{ "msg1": { "message": "Hello" } }',
      // Invalid JSON: trailing comma, missing quote
      'locales/ja.json': '{ "msg1": { "message": "Hello", "translation": "bad json }',
    })

    let output = ''
    let exitCode = 0
    try {
      output = execSync(
        `node ${CLI} compile --config ${join(tmpDir, 'fluenti.config.ts')} 2>&1`,
        { cwd: tmpDir, encoding: 'utf-8', timeout: 30_000, env: cliEnv() },
      )
    } catch (err: any) {
      exitCode = err.status ?? 1
      output = String(err.stdout ?? '') + String(err.stderr ?? '') + String(err.message ?? '')
    }

    // CLI should exit with non-zero or at least report the error
    // The key assertion: it does NOT crash with an unhandled exception
    expect(typeof output).toBe('string')
    if (exitCode !== 0) {
      // Error output should mention something about JSON or parse
      expect(output.toLowerCase()).toMatch(/json|parse|syntax|error|invalid|unexpected/)
    }
  })

  it('PO catalog with malformed entries: compile reports error, does not crash', () => {
    tmpDir = createProject({
      'fluenti.config.ts': makeConfig(['en', 'ja'], 'po'),
      'locales/en.po': [
        '# English catalog',
        'msgid "Hello"',
        'msgstr ""',
        '',
      ].join('\n'),
      // Malformed PO: no proper msgid/msgstr structure
      'locales/ja.po': [
        '# Broken PO file',
        'this is not valid PO format at all',
        'msgid "Hello"',
        '--- missing msgstr ---',
        '',
      ].join('\n'),
    })

    let output = ''
    let exitCode = 0
    try {
      output = execSync(
        `node ${CLI} compile --config ${join(tmpDir, 'fluenti.config.ts')} 2>&1`,
        { cwd: tmpDir, encoding: 'utf-8', timeout: 30_000, env: cliEnv() },
      )
    } catch (err: any) {
      exitCode = err.status ?? 1
      output = String(err.stdout ?? '') + String(err.stderr ?? '') + String(err.message ?? '')
    }

    // Should not crash with unhandled exception
    expect(typeof output).toBe('string')
    // Either succeeds (gracefully handling the malformed file) or exits with error
    // In both cases the process completed without a hard crash
    expect(exitCode === 0 || exitCode === 1).toBe(true)
  })

  it('source file with syntax error: extract warns and skips file', () => {
    tmpDir = createProject({
      'fluenti.config.ts': makeConfig(['en', 'ja']),
      // Valid source file
      'src/good.tsx': `
        import { msg } from '@fluenti/react'
        export const A = msg\`Good message\`
      `,
      // Broken source file (unclosed template literal, bad syntax)
      'src/bad.tsx': `
        import { msg from '@fluenti/react'
        export const B = msg\`Broken message
      `,
    })

    let output = ''
    let exitCode = 0
    try {
      output = execSync(
        `node ${CLI} extract --config ${join(tmpDir, 'fluenti.config.ts')} 2>&1`,
        { cwd: tmpDir, encoding: 'utf-8', timeout: 30_000, env: cliEnv() },
      )
    } catch (err: any) {
      exitCode = err.status ?? 1
      output = String(err.stdout ?? '') + String(err.stderr ?? '') + String(err.message ?? '')
    }

    // The process should complete (not crash)
    expect(typeof output).toBe('string')

    // If it succeeded (exit 0), the good message should still be extracted
    if (exitCode === 0) {
      try {
        const enRaw = readFileSync(join(tmpDir, 'locales/en.json'), 'utf-8')
        const enCatalog = JSON.parse(enRaw)
        const messages = Object.values(enCatalog).map((e: any) => e.message as string)
        expect(messages).toContain('Good message')
      } catch {
        // Catalog might not be created if entire extract failed — that is acceptable
      }
    }
  })
})
