// Auto-generated by @fluenti/next — do not edit
import type { ReactNode, ReactElement } from 'react'

export declare function ClientI18nProvider(props: {
  locale: string
  fallbackLocale: string
  fallbackChain?: Record<string, string[]>
  children: ReactNode
}): ReactElement
