// Auto-generated by @fluenti/next — do not edit
import { createServerI18n } from '@fluenti/react/server'
import { createElement } from 'react'
import __resolveLocale from '../src/lib/resolve-locale'

const __locales = ["en","ja","zh-CN"]

const serverI18n = createServerI18n({
  loadMessages: async (locale) => {
    switch (locale) {
      case 'en': return import('../src/locales/compiled/en')
      case 'ja': return import('../src/locales/compiled/ja')
      case 'zh-CN': return import('../src/locales/compiled/zh-CN')
      default: return import('../src/locales/compiled/en')
    }
  },
  fallbackLocale: 'en',
  fallbackChain: undefined,
  resolveLocale: __resolveLocale,
})

export const setLocale = serverI18n.setLocale
export const getI18n = serverI18n.getI18n
export const t = (..._args) => {
  throw new Error(
    "[fluenti] `t` imported from '@fluenti/next' is a compile-time API replaced at build time.\n" +
      '  Ensure:\n' +
      '  1. `withFluenti()` is configured in next.config.ts\n' +
      '  2. The file is inside src/ (not node_modules)\n' +
      "  3. For client components, import from '@fluenti/react'",
  )
}
export const Trans = serverI18n.Trans
export const Plural = serverI18n.Plural
export const Select = serverI18n.Select
export const DateTime = serverI18n.DateTime
export const NumberFormat = serverI18n.NumberFormat

/**
 * Async server component for root layouts.
 *
 * Sets up both server-side (React.cache) and client-side (I18nProvider) i18n.
 */
export async function I18nProvider({ locale, children }) {
  const activeLocale = locale ?? 'en'

  // 1. Initialize server-side i18n (React.cache scoped)
  serverI18n.setLocale(activeLocale)
  await serverI18n.getI18n()

  // 2. Import the local 'use client' provider that has messages statically bundled.
  // Messages contain functions (interpolation) which can't be serialized across the RSC boundary.
  const { ClientI18nProvider } = await import('./client-provider.js')

  return createElement(ClientI18nProvider, {
    locale: activeLocale,
    fallbackLocale: 'en',
    fallbackChain: undefined,
  }, children)
}
