// Auto-generated by @fluenti/next — do not edit
import type { ReactNode, ReactElement } from 'react'
import type { CompileTimeT, FluentInstanceExtended } from '@fluenti/core'

export declare function setLocale(locale: string): void
export declare function getI18n(): Promise<FluentInstanceExtended & { locale: string }>
export declare const t: CompileTimeT

export declare function Trans(props: {
  children: ReactNode
  id?: string
  context?: string
  comment?: string
  render?: (translation: ReactNode) => ReactNode
}): Promise<ReactElement>

export declare function Plural(props: {
  value: number
  id?: string
  context?: string
  comment?: string
  zero?: ReactNode
  one?: ReactNode
  two?: ReactNode
  few?: ReactNode
  many?: ReactNode
  other: ReactNode
  offset?: number
}): Promise<ReactElement>

export declare function Select(props: {
  value: string
  id?: string
  context?: string
  comment?: string
  other: ReactNode
  options?: Record<string, ReactNode>
  [key: string]: ReactNode | Record<string, ReactNode> | string | undefined
}): Promise<ReactElement>

export declare function DateTime(props: {
  value: Date | number
  style?: string
}): Promise<ReactElement>

export declare function NumberFormat(props: {
  value: number
  style?: string
}): Promise<ReactElement>

export declare function I18nProvider(props: {
  locale?: string
  children: ReactNode
}): Promise<ReactElement>
