import { describe, it, expect, vi, beforeEach } from 'vitest'
import { generateServerModule } from '../src/generate-server-module'
import type { ResolvedFluentConfig } from '../src/types'

// Track written files
const writtenFiles: Record<string, string> = {}

vi.mock('node:fs', () => ({
  writeFileSync: vi.fn((path: string, content: string) => {
    writtenFiles[path] = content
  }),
  mkdirSync: vi.fn(),
  existsSync: vi.fn(() => true),
}))

describe('generateServerModule', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    for (const key of Object.keys(writtenFiles)) {
      delete writtenFiles[key]
    }
  })

  const baseConfig: ResolvedFluentConfig = {
    fluentiConfig: {
      sourceLocale: 'en',
      locales: ['en', 'ja'],
      catalogDir: './locales',
      format: 'po',
      include: ['./src/**/*.{vue,tsx,jsx,ts,js}'],
      compileOutDir: './src/locales/compiled',
    },
    serverModule: null,
    serverModuleOutDir: 'node_modules/.fluenti',
    cookieName: 'locale',
    runtimeInterpolate: false,
  }

  it('generates a valid JS module file', () => {
    const result = generateServerModule('/project', baseConfig)
    expect(result).toBe('/project/node_modules/.fluenti/server.js')

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']
    expect(serverSource).toBeDefined()
    expect(serverSource).toContain('// Auto-generated by @fluenti/next')
    expect(serverSource).toContain("import { createServerI18n } from '@fluenti/react/server'")
  })

  it('generates locale-specific client provider chunks', () => {
    generateServerModule('/project', baseConfig)

    expect(writtenFiles['/project/node_modules/.fluenti/client-provider.js']).toBeDefined()
    expect(writtenFiles['/project/node_modules/.fluenti/client-provider-en.js']).toBeDefined()
    expect(writtenFiles['/project/node_modules/.fluenti/client-provider-ja.js']).toBeDefined()
  })

  it('contains loadMessages function with locale switch cases', () => {
    generateServerModule('/project', baseConfig)

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain('loadMessages')
    expect(serverSource).toContain("case 'en':")
    expect(serverSource).toContain("case 'ja':")
    expect(serverSource).toContain('default:')
  })

  it('contains setLocale and getI18n exports', () => {
    generateServerModule('/project', baseConfig)

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain('export const setLocale = serverI18n.setLocale')
    expect(serverSource).toContain('export const getI18n = serverI18n.getI18n')
    expect(serverSource).toContain('export const Select = serverI18n.Select')
    expect(serverSource).not.toContain('__getServerI18n')
    expect(serverSource).toContain('export async function I18nProvider')
  })

  it('omits runtime interpolate imports by default', () => {
    generateServerModule('/project', baseConfig)

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    const clientSource = writtenFiles['/project/node_modules/.fluenti/client-provider.js']!

    expect(serverSource).not.toContain("from '@fluenti/core/runtime'")
    expect(serverSource).not.toContain('interpolate: __interpolate')
    expect(clientSource).not.toContain("from '@fluenti/core/runtime'")
    expect(clientSource).not.toContain('interpolate: __interpolate')
  })

  it('includes runtime interpolate when explicitly enabled', () => {
    generateServerModule('/project', {
      ...baseConfig,
      runtimeInterpolate: true,
    })

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    const clientSource = writtenFiles['/project/node_modules/.fluenti/client-provider.js']!

    expect(serverSource).toContain("import { interpolate as __interpolate } from '@fluenti/core/runtime'")
    expect(serverSource).toContain('interpolate: __interpolate')
    expect(clientSource).toContain("import { interpolate as __interpolate } from '@fluenti/core/runtime'")
    expect(clientSource).toContain('interpolate: __interpolate')
  })

  it('generates __locales array from config', () => {
    generateServerModule('/project', baseConfig)

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain('const __locales = ["en","ja"]')
  })

  it('uses multi-layer resolveLocale fallback by default', () => {
    generateServerModule('/project', baseConfig)

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    // Should contain middleware header check
    expect(serverSource).toContain("headerStore.get('x-fluenti-locale')")
    // Should contain cookie check with default name
    expect(serverSource).toContain("cookieStore.get('locale')")
    // Should contain accept-language check
    expect(serverSource).toContain("headerStore.get('accept-language')")
    // Should not use custom resolveLocale
    expect(serverSource).not.toContain('__resolveLocale')
  })

  it('respects custom cookieName', () => {
    generateServerModule('/project', {
      ...baseConfig,
      cookieName: 'NEXT_LOCALE',
    })

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain("cookieStore.get('NEXT_LOCALE')")
    expect(serverSource).not.toContain("cookieStore.get('locale')")
  })

  it('generates accept-language parsing in default resolveLocale', () => {
    generateServerModule('/project', baseConfig)

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain("acceptLang.split(',')")
    expect(serverSource).toContain("part.split(';')[0].trim()")
    expect(serverSource).toContain("lang.split('-')[0]")
  })

  it('imports custom resolveLocale module when path is provided', () => {
    generateServerModule('/project', {
      ...baseConfig,
      resolveLocale: './lib/resolve-locale',
    })

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain("import __resolveLocale from '../../lib/resolve-locale'")
    expect(serverSource).toContain('resolveLocale: __resolveLocale,')
    // Should skip the default multi-layer fallback
    expect(serverSource).not.toContain("headerStore.get('x-fluenti-locale')")
    expect(serverSource).not.toContain("cookieStore.get('locale')")
  })

  it('escapes quotes in generated import paths for compiled catalogs', () => {
    generateServerModule('/project', {
      ...baseConfig,
      fluentiConfig: {
        ...baseConfig.fluentiConfig,
        compileOutDir: "./src/compiled's",
      },
    })

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    const clientSource = writtenFiles['/project/node_modules/.fluenti/client-provider-en.js']!

    expect(serverSource).toContain("case 'en': return import('../../src/compiled\\'s/en')")
    expect(serverSource).toContain("default: return import('../../src/compiled\\'s/en')")
    expect(clientSource).toContain("import __messages_en from '../../src/compiled\\'s/en'")
  })

  it('escapes quotes in custom resolveLocale import path', () => {
    generateServerModule('/project', {
      ...baseConfig,
      resolveLocale: "./lib/resolve'locale",
    })

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain("import __resolveLocale from '../../lib/resolve\\'locale'")
  })

  // ── Template injection / escaping ──────────────────────────────────────
  it('escapes single quotes in cookieName to prevent JS injection', () => {
    generateServerModule('/project', {
      ...baseConfig,
      cookieName: "loc'ale",
    })
    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    // Should contain escaped value, not a broken string literal
    expect(serverSource).toContain("cookieStore.get('loc\\'ale')")
    expect(serverSource).not.toContain("cookieStore.get('loc'ale')")
  })

  it('escapes backslashes in cookieName', () => {
    generateServerModule('/project', {
      ...baseConfig,
      cookieName: 'loc\\ale',
    })
    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain("cookieStore.get('loc\\\\ale')")
  })

  it('adds @ts-nocheck to generated server.js and client-provider.js', () => {
    generateServerModule('/project', baseConfig)
    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    const clientSource = writtenFiles['/project/node_modules/.fluenti/client-provider.js']!
    const localeClientSource = writtenFiles['/project/node_modules/.fluenti/client-provider-en.js']!
    expect(serverSource).toContain('// @ts-nocheck')
    expect(clientSource).toContain('// @ts-nocheck')
    expect(localeClientSource).toContain('// @ts-nocheck')
  })

  it('generates client-provider.d.ts with ClientI18nProvider declaration', () => {
    generateServerModule('/project', baseConfig)
    const dts = writtenFiles['/project/node_modules/.fluenti/client-provider.d.ts']!
    expect(dts).toBeDefined()
    expect(dts).toContain('ClientI18nProvider')
    expect(dts).toContain('locale: string')
    expect(dts).toContain('children: ReactNode')
  })

  // ── x-fluenti-locale header in default resolveLocale ──────────────────
  it('reads x-fluenti-locale header as highest-priority in default resolveLocale', () => {
    generateServerModule('/project', baseConfig)
    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    // x-fluenti-locale check must appear before the cookie check
    const headerIdx = serverSource.indexOf("headerStore.get('x-fluenti-locale')")
    const cookieIdx = serverSource.indexOf("cookieStore.get('locale')")
    expect(headerIdx).toBeGreaterThan(-1)
    expect(cookieIdx).toBeGreaterThan(-1)
    expect(headerIdx).toBeLessThan(cookieIdx)
  })

  it('validates x-fluenti-locale against __locales before using it', () => {
    generateServerModule('/project', baseConfig)
    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    // The generated code should check that fromMiddleware is in __locales
    expect(serverSource).toMatch(/fromMiddleware.*__locales\.includes/)
  })

  // ── i18n-config.js generation ─────────────────────────────────────────
  it('generates i18n-config.js with locales, sourceLocale, cookieName', () => {
    generateServerModule('/project', baseConfig)
    const configSource = writtenFiles['/project/node_modules/.fluenti/i18n-config.js']!
    expect(configSource).toBeDefined()
    expect(configSource).toContain('export const locales = ["en","ja"]')
    expect(configSource).toContain("export const sourceLocale = 'en'")
    expect(configSource).toContain("export const cookieName = 'locale'")
  })

  it('generates i18n-config.d.ts with type declarations', () => {
    generateServerModule('/project', baseConfig)
    const dts = writtenFiles['/project/node_modules/.fluenti/i18n-config.d.ts']!
    expect(dts).toBeDefined()
    expect(dts).toContain('export declare const locales: string[]')
    expect(dts).toContain('export declare const sourceLocale: string')
    expect(dts).toContain('export declare const cookieName: string')
  })

  it('i18n-config.js uses custom cookieName when provided', () => {
    generateServerModule('/project', { ...baseConfig, cookieName: 'NEXT_LOCALE' })
    const configSource = writtenFiles['/project/node_modules/.fluenti/i18n-config.js']!
    expect(configSource).toContain("export const cookieName = 'NEXT_LOCALE'")
  })

  // ── dateFormats / numberFormats in ClientI18nProvider ─────────────────
  it('passes dateFormats to generated ClientI18nProvider', () => {
    generateServerModule('/project', {
      ...baseConfig,
      fluentiConfig: {
        ...baseConfig.fluentiConfig,
        dateFormats: { short: { dateStyle: 'short' } },
      },
    })
    const clientSource = writtenFiles['/project/node_modules/.fluenti/client-provider.js']!
    expect(clientSource).toContain('"short"')
    expect(clientSource).toContain('__dateFormats')
    expect(clientSource).toContain('dateFormats: __dateFormats')
  })

  it('passes numberFormats to generated ClientI18nProvider', () => {
    generateServerModule('/project', {
      ...baseConfig,
      fluentiConfig: {
        ...baseConfig.fluentiConfig,
        numberFormats: { currency: { style: 'currency', currency: 'USD' } },
      },
    })
    const clientSource = writtenFiles['/project/node_modules/.fluenti/client-provider.js']!
    expect(clientSource).toContain('"USD"')
    expect(clientSource).toContain('__numberFormats')
    expect(clientSource).toContain('numberFormats: __numberFormats')
  })

  it('sets dateFormats to undefined when not configured', () => {
    generateServerModule('/project', baseConfig)
    const clientSource = writtenFiles['/project/node_modules/.fluenti/client-provider.js']!
    expect(clientSource).toContain('const __dateFormats = undefined')
    expect(clientSource).toContain('const __numberFormats = undefined')
  })

  it('loads non-initial locales lazily in locale-specific client providers', () => {
    generateServerModule('/project', {
      ...baseConfig,
      fluentiConfig: {
        ...baseConfig.fluentiConfig,
        locales: ['en', 'ja', 'zh-CN'],
      },
    })

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    const enProvider = writtenFiles['/project/node_modules/.fluenti/client-provider-en.js']!
    const jaProvider = writtenFiles['/project/node_modules/.fluenti/client-provider-ja.js']!

    expect(serverSource).toContain("case 'ja': return import('./client-provider-ja.js')")
    expect(serverSource).toContain("case 'zh-CN': return import('./client-provider-zh_CN.js')")
    expect(enProvider).toContain("import __messages_en from '../../src/locales/compiled/en'")
    expect(enProvider).toContain("case 'zh-CN': return import('../../src/locales/compiled/zh-CN')")
    expect(jaProvider).toContain("import __messages_ja from '../../src/locales/compiled/ja'")
    expect(jaProvider).toContain("import __messages_en from '../../src/locales/compiled/en'")
  })

  // ── writeFileSync error handling ──────────────────────────────────────
  it('throws a Fluenti-specific error when writeFileSync fails', async () => {
    const fsMod = await import('node:fs')
    vi.mocked(fsMod.writeFileSync).mockImplementationOnce(() => {
      throw new Error('ENOSPC: no space left on device')
    })
    expect(() => generateServerModule('/project', baseConfig)).toThrow(
      '[fluenti] Failed to write generated module',
    )
  })
})
