import { describe, it, expect, vi, beforeEach } from 'vitest'
import { generateServerModule } from '../src/generate-server-module'

// Track written files
const writtenFiles: Record<string, string> = {}

vi.mock('node:fs', () => ({
  writeFileSync: vi.fn((path: string, content: string) => {
    writtenFiles[path] = content
  }),
  mkdirSync: vi.fn(),
  existsSync: vi.fn(() => true),
}))

describe('generateServerModule', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    for (const key of Object.keys(writtenFiles)) {
      delete writtenFiles[key]
    }
  })

  const baseConfig = {
    locales: ['en', 'ja'],
    defaultLocale: 'en',
    compiledDir: './src/locales/compiled',
    serverModule: null,
    serverModuleOutDir: 'node_modules/.fluenti',
  }

  it('generates a valid JS module file', () => {
    const result = generateServerModule('/project', baseConfig)
    expect(result).toBe('/project/node_modules/.fluenti/server.js')

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']
    expect(serverSource).toBeDefined()
    expect(serverSource).toContain('// Auto-generated by @fluenti/next')
    expect(serverSource).toContain("import { createServerI18n } from '@fluenti/react/server'")
  })

  it('contains loadMessages function with locale switch cases', () => {
    generateServerModule('/project', baseConfig)

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain('loadMessages')
    expect(serverSource).toContain("case 'en':")
    expect(serverSource).toContain("case 'ja':")
    expect(serverSource).toContain('default:')
  })

  it('contains setLocale and getI18n exports', () => {
    generateServerModule('/project', baseConfig)

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain('export const setLocale = serverI18n.setLocale')
    expect(serverSource).toContain('export const getI18n = serverI18n.getI18n')
    expect(serverSource).toContain('export const Select = serverI18n.Select')
    expect(serverSource).not.toContain('__getServerI18n')
    expect(serverSource).toContain('export async function I18nProvider')
  })

  it('uses cookie-based resolveLocale by default', () => {
    generateServerModule('/project', baseConfig)

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain("(await cookies()).get('locale')")
    expect(serverSource).not.toContain('__resolveLocale')
  })

  it('imports custom resolveLocale module when path is provided', () => {
    generateServerModule('/project', {
      ...baseConfig,
      resolveLocale: './lib/resolve-locale',
    })

    const serverSource = writtenFiles['/project/node_modules/.fluenti/server.js']!
    expect(serverSource).toContain("import __resolveLocale from '../../lib/resolve-locale'")
    expect(serverSource).toContain('resolveLocale: __resolveLocale,')
    expect(serverSource).not.toContain("cookies().get('locale')")
  })
})
